media: assets
Content: 
    name: posts 
    label: Posts 
    type: Collection 
    path: _posts 
    fields: 
        - {name: title:=, label: Title, type: string} 
        - {name: layout, type: string, hidden: true, default: post}
        - {name: date, label: Date, type: date }
        - {name: image, image: assets/img/blog-3.jpeg }
        - {name: tags, type: string, label: tags, type: string} 
        - {name: category, type: string label: category, type: string}
