name = "inboxsmarts"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
SITE_URL = "https://inboxsmarts.com"
INTAKE_EMAIL_TO = "hello@inboxsmarts.com"
INTAKE_EMAIL_FROM = "InboxSmarts <onboarding@inboxsmarts.com>"

# Uncomment when deploying to custom domain
# [[routes]]
# pattern = "inboxsmarts.com/*"
# zone_name = "inboxsmarts.com"
